### ISSUE TITLE
runtime calculation needs unit

### ISSUE THREAD

**Issue by schochastics** [domagal9/backbone#12]
There is an issue with the runtime output

```r
# remotes::install.github("schochastics/levelnet")
data("cosponsor_senate_15",package="levelnet")
g <- levelnet::bipartite_from_data_frame(cosponsor_senate_15,"bill","name")
system.time(B <- backbone::sdsm(g))
#> user  system elapsed 
#> 163.833   0.938 164.748

B$summary$`Model Summary`[12] # stores runtime
#> 2.75

system.time(B <- backbone::sdsm(g,model="logit"))
#>   user  system elapsed 
#>  6.437   0.028   6.462 

B$summary$`Model Summary`[12]
#> 6.34
```
The current output suggests that the default 'polytope' is faster than 'logit', which is obviously not true.

`total.time = (round(difftime(run.time.end, run.time.start), 2))`
should probably be changed to 
`total.time = (round(difftime(run.time.end, run.time.start,units = "secs"), 2))`

**Comment by domagal9** [comment]
Good catch, thanks David!

updated on develop, to be integrated in v1.2.1
