### ISSUE TITLE
Problem with non-ordinal weights being caught

### ISSUE THREAD

**Issue by reuning** [domagal9/backbone#38]
As a bad practitioner I didn't read the documentation that closely and started just throwing data into this. I ran into a small issue caused by this: https://github.com/zpneal/backbone/blob/b3615881471bc0583c6dacfe93e0490058a7b6e4/R/osdsm.R#L81

The short version is that I was using interval weights. This line fails though if you have gaps between 0 and the maximum weight. For example if the weights are 0,1,2,3,6,7. The error message though isn't helpful: `Error in !all.equal(weights, c(0:max(weights))) : invalid argument type`

I'm not sure how you want to fix this, but the below code would catch my problem and catch any use of fractional weights.  

```
if ( (max(weights) + 1) != length(unique(weights)) | any(weights != round(weights)) ) {stop("Edge weights must be measured on an ordinal scale starting with 0")}
```

**Comment by zpneal** [comment]
Thanks for catching that! The version in the `devel` branch now allows values in the ordinal edge weight scale to not actually occur in the network. Seems to be working, but let me know if you run into problems.
