### ISSUE TITLE
dgCMatrix support

### ISSUE THREAD

**Issue by PCK1992** [domagal9/backbone#4]
Is it possible to implement this? I have a large graph and the matrix representation is automatically saved as a dgCMatrix. In my case, I can't convert it into a regular matrix.

**Comment by domagal9** [comment]
Hello,

The current GitHub version has sparse matrix support, while CRAN version 1.0.0 does not. Does the GitHub version work for your dgCMatrix? It will implemented in our next CRAN update (hopefully about a week or two out).

**Comment by PCK1992** [comment]
Worked! I can't use it for my network due to memory issues but the error disappeared. Thank you!
