### ISSUE TITLE
new igraph errors 

### ISSUE THREAD

**Issue by schochastics** [domagal9/backbone#44]
see: https://github.com/igraph/rigraph/pull/633#issuecomment-1384205381

Hope it is ok I open an issue for this. The problem is here:
https://github.com/zpneal/backbone/blob/release/inst/tinytest/test_backbone.R#L77

Solution should be to
change: `igraph::V(M)$names <- LETTERS[1:10]` to:`igraph::V(M)$names <- c(LETTERS[1:10],1:100)`

**Comment by zpneal** [comment]
Thanks! Made the fix.
