### ISSUE TITLE
scobit model for sdsm

### ISSUE THREAD

**Issue by schochastics** [domagal9/backbone#7]
Any plans to include the scobit model for sdsm at one point?
Always find it to produce the best fit, especially for really sparse networks.
I implemented the model for my version of the sdsm [here](https://github.com/schochastics/levelnet/blob/master/R/sdsm.R#L53) and [here](https://github.com/schochastics/levelnet/blob/master/src/scobit.cpp).

Happy to contribute the code (via a pull request) since I am not really developing that package at the moment and I want to repurpose it eventually.

**Comment by domagal9** [comment]
Hi David, 

I'd love to include it! That would be fantastic if you could submit a pull request. 

Thank you!
Rachel

**Comment by domagal9** [comment]
merged into develop branch May 26th, to be added to backbone v1.2.1
